
#ifndef _DEFAULT_H
#define _DEFAULT_H

#define MAX_INT						0x7FFFFFFF
#define INFINITE_VALUE				MAX_INT

#define DEFAULT_NUM_ANTS			10
#define DEFAULT_ALPHA				1.0f
#define DEFAULT_BETA				5.0f
#define DEFAULT_RHO					0.1f
#define DEFAULT_MAX_TIME			INFINITE_VALUE
#define DEFAULT_MAX_ITERATIONS		10
#define DEFAULT_MAX_REPITITIONS		INFINITE_VALUE
#define DEFAULT_OPTIMUM				-1
#define DEFAULT_PHEROMONE			0.000001
#define MIN_PHEROMONE				0.000000000000000001

#define DEFAULT_NUM_RANK_ANTS		5




/// ants aging parameters
/*
#define DEFAULT_MIN_RITIREMENT_AGE		5
#define DEFAULT_MAX_RITIREMENT_AGE		20
#define DEFAULT_LOCAL_NO_CONVERGENCE	2
#define DEFAULT_GLOBAL_NO_CONVERGENCE	5
#define DEFAULT_MIN_POPULATION_LIMIT	50
#define DEFAULT_MAX_POPULATION_LIMIT	100
*/

#define DEFAULT_MIN_RITIREMENT_AGE		30
#define DEFAULT_MAX_RITIREMENT_AGE		50
#define DEFAULT_LOCAL_NO_CONVERGENCE	10
#define DEFAULT_GLOBAL_NO_CONVERGENCE	10
#define DEFAULT_MIN_POPULATION_LIMIT	40
#define DEFAULT_MAX_POPULATION_LIMIT	100


#endif // _DEFAULT_H